[versions]
kotlin = "1.9.24"
agp = "8.6.0"

coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.1"
constraintlayout = "2.1.4"
navigation = "2.8.6"

compose = "1.6.4"
material3Android = "1.3.2"

media3CommonKtx = "1.6.1"
coil = "2.4.0"

playServicesMaps = "19.2.0"
places = "4.2.0"

room = "2.6.1"
work = "2.9.0"


junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
jetbrainsKotlinJvm = "1.9.24"

chatlib = "1.2.4"
junitKtx = "1.2.1"

ksp = "1.9.24-1.0.20"




[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3CommonKtx" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
places = { group = "com.google.android.libraries.places", name = "places", version.ref = "places" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}
work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work"}
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
chatlib = { group = "com.github.Yermakhan05", name = "chatlib", version.ref = "chatlib" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

